version: 0.0.{build}-{branch}
pull_requests:
  do_not_increment_build_number: true
configuration: Release
build:
  verbosity: minimal
cache: 
- 'C:\projects\MarkDocs\scripts\tools'
build_script:
- ps: '& ./build.ps1'
- ps: '& ./push-choco.ps1'
test: off
artifacts:
- path: artifacts\**\*.nupkg
- path: artifacts\**\*.zip
environment:
  CHOCO_API_KEY:
    secure: DLPmZhl7Zr4qqU3JIzGsA4opRPGjNZZkH/MSkOQKbL8iYyf7+sSFmG418+QjeUy2
deploy:
- provider: NuGet
  api_key:
    secure: r5vF3QENzP28+dU6gvmD7Sqbdt5Ti43yhuSye3O7TJxKT+6vuponJ7tVwkGkotH7
  on:
    branch: master
  skip_symbols: false
  artifact: artifacts\ITGlobal.*.nupkg
notifications:
- provider: Slack
  incoming_webhook: a7TE9Xu2mdPphDJSk5r/BQn+2npcVDiJIrzR8tYselHQvWmSleO8NGdGVaLAxVw6yhVyzQh2IT9rEDXYssazCgdoW96THTdfjK2X2e0iLzk=
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false 