version: 0.0.{build}-{branch}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2019
configuration: Release
build:
  verbosity: minimal
build_script:
- ps: '& ./build.ps1 all'
test: 'off'
artifacts:
- path: artifacts\**\*.nupkg
environment:
  CHOCO_PUSH_PUBLIC: 0
  CHOCO_PUSH_PRIVATE: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  CHOCO_API_KEY:
    secure: DLPmZhl7Zr4qqU3JIzGsA4opRPGjNZZkH/MSkOQKbL8iYyf7+sSFmG418+QjeUy2
  NUGET_API_KEY:
    secure: DbIM3c1ql3w0hU3WYPgUwkU+rBI/tFQG0oClw8sMu1ow8LQ0lQGYNFtiZfKk59tx
  CHOCO_PRIVATE_URL:
    secure: PbtRYek+AtjgpV7a2nkfX0UzwpAcZhP+xUU9eA3hXo4982NzrZV6/LmvBmANEwFszUupJpKJoeA1FPPJKx6sZA==
  CHOCO_PRIVATE_API_KEY:
    secure: +otm426DP2sxI+6uwbY9OKDwwo9GHQOmNjk1AcDgL0nroXmr0YQs7Z8A7Xy6hVPm
#deploy:
#- provider: NuGet
#  api_key:
#    secure: DbIM3c1ql3w0hU3WYPgUwkU+rBI/tFQG0oClw8sMu1ow8LQ0lQGYNFtiZfKk59tx
#  skip_symbols: false
#  on:
#    appveyor_repo_tag: true
deploy_script:
- ps: '& ./push.ps1 all'
notifications:
- provider: Slack
  incoming_webhook: a7TE9Xu2mdPphDJSk5r/BQn+2npcVDiJIrzR8tYselHQvWmSleO8NGdGVaLAxVw6yhVyzQh2IT9rEDXYssazCgdoW96THTdfjK2X2e0iLzk=
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false 
